config/routes.rb
Rails.application.routes.draw do
  resources :events
  root to: redirect("/events")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filter_scopeable.rb
# frozen_string_literal: true

module FilterScopeable
  extend ActiveSupport::Concern

  def filter_scope(name, block)
    define_method(name) do |filter_value|
      return self if filter_value.blank?

      instance_exec(filter_value, &block)
    end
  end
end

app/models/concerns/filterable_model.rb
# frozen_string_literal: true

module FilterableModel
  extend ActiveSupport::Concern

  def filter_proxy
    raise "
      Model #{name} including FilterableModel concern requires filter_proxy method to be defined.
      Method should return filter proxy class associated to model.
    "
  end

  delegate :filter_by, to: :filter_proxy
end

app/models/concerns/filters/event_filter_proxy.rb
# frozen_string_literal: true

module Filters
  module EventFilterScopes
    extend FilterScopeable

    filter_scope :start_from, ->(start_date) { where('start >= ?', start_date) }
    filter_scope :start_to, ->(start_date) { where('start <= ?', start_date) }
    filter_scope :finish_from, ->(finish_date) { where('finish >= ?', finish_date) }
    filter_scope :finish_to, ->(finish_date) { where('finish <= ?', finish_date) }
    filter_scope :event_type, ->(id) { where(event_type_id: id) }
    filter_scope :customer, ->(id) { where(customer_id: id) }
  end

  class EventFilterProxy < FilterProxy
    def self.query_scope
      Event
    end

    def self.filter_scopes_module
      Filters::EventFilterScopes
    end
  end
end

app/models/concerns/filters/filter_proxy.rb
# frozen_string_literal: true

module Filters
  class FilterProxy
    extend FilterScopeable

    class << self
      def query_scope
        raise "Class #{name} does not define query_scope class method."
      end

      def filter_scopes_module
        raise "Class #{name} does not define filter_scopes_module class method."
      end

      def filter_by(**filters)
        extended_scope = query_scope.extending(filter_scopes_module)

        filters.each do |filter_scope, filter_value|
          if filter_value.present? && extended_scope.respond_to?(filter_scope)
            extended_scope = extended_scope.send(filter_scope, filter_value)
          end
        end

        extended_scope
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_person_name
  has_many :events
end

# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  first_name :string           not null
#  last_name  :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/event.rb
class Event < ApplicationRecord
  extend FilterableModel

  belongs_to :customer
  belongs_to :event_type
  validates :start, :finish, presence: true

  class << self
    def filter_proxy
      Filters::EventFilterProxy
    end
  end
end

# == Schema Information
#
# Table name: events
#
#  id            :integer          not null, primary key
#  finish        :datetime         not null
#  start         :datetime         not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  customer_id   :integer
#  event_type_id :integer
#
# Indexes
#
#  index_events_on_customer_id    (customer_id)
#  index_events_on_event_type_id  (event_type_id)
#
# Foreign Keys
#
#  customer_id    (customer_id => customers.id) ON DELETE => cascade
#  event_type_id  (event_type_id => event_types.id) ON DELETE => cascade
#

app/models/event_type.rb
class EventType < ApplicationRecord
  has_many :events
end

# == Schema Information
#
# Table name: event_types
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/filterable_controller.rb
# frozen_string_literal: true

module FilterableController
  extend ActiveSupport::Concern

  def filter(scope, filters = filter_params)
    unless scope.respond_to?(:filter_by)
      raise "
        Controller #{self.class.name} tried to filter a scope of type #{scope.class.name}.
        Scope class does not extend FilterProxy interface.
      "
    end

    scope.filter_by(**filters)
  end

  def filter_params
    raise "FilterableModel controller #{self.class.name} does not define filter_params method."
  end

  included do
    helper_method :filter_params
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :initialize_event, only: [:new, :create]
  before_action :set_event, only: [:edit, :update, :destroy, :show]

  include FilterableController

  def index
    @events = filter(Event.all.includes(:customer, :event_type).order(start: :asc))
  end

  def new
  end

  def create
    if @event.update event_params
      redirect_to events_path
    else
      render :edit
    end
  end

  def edit
  end

  def update
    if @event.update event_params
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  def show
  end

  private

  def initialize_event
    @event = Event.new(
      start: DateTime.now.beginning_of_hour + 1.hour,
      finish: DateTime.now.beginning_of_hour + 3.hours
    )
  end

  def set_event
    @event = Event.find params[:id]
  end

  def event_params
    params.require(:event).permit(
      :event_type_id,
      :customer_id,
      :start,
      :finish
    )
  end

  def filter_params
    {
      start_from: time_value(params, 'start_from'),
      start_to: time_value(params, 'start_to'),
      finish_from: time_value(params, 'finish_from'),
      finish_to: time_value(params, 'finish_to'),
      event_type: params['event_type']&.reject(&:empty?),
      customer: params['customer']&.reject(&:empty?)
    }
  end

  def time_value(hash, field)
    Time.zone.local(*(1..5).map { |i| hash["#{field}(#{i}i)"] })
  rescue ArgumentError, TypeError
    # if datetime value is not searched
    nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<div class="mx-auto px-8 py-6 rounded shadow bg-white">
  <%= form_with model: @event do |f| %>
    <div class="flex flex-col space-y-4">
      <div class="flex items-center justify-between bg-gray-100 py-3 px-6 rounded">
        <div><%= f.label :event_type_id, "Event Theme", class: "font-bold" %></div>
        <div><%= f.select :event_type_id, EventType.order(:name).pluck(:name, :id), {}, { class: "form-select" } %></div>
      </div>

      <div class="flex items-center justify-between bg-gray-100 py-3 px-6 rounded">
        <div><%= f.label :customer_id, class: "font-bold" %></div>
        <div><%= f.select :customer_id, Customer.order(:first_name).map { |c| [c.name, c.id] }, {}, { class: "form-select" } %></div>
      </div>

      <div class="flex items-center justify-between bg-gray-100 py-3 px-6 rounded">
        <%= f.label :start, class: "font-bold" %>
        <div class="row">
          <%= f.datetime_select :start, {}, { class: "form-select form-select-sm col mr-1 ml-1 w-auto" } %>
        </div>
      </div>

      <div class="flex items-center justify-between bg-gray-100 py-3 px-6 rounded">
        <%= f.label :finish, class: "font-bold" %>
        <div class="row">
          <%= f.datetime_select :finish, {}, { class: "form-select form-select-sm col mr-1 ml-1 w-auto" }  %>
        </div>
      </div>

      <div class="flex justify-between mt-4">
        <div>
          <% if @event.persisted? %>
            <%= link_to "Cancel Event", event_path(@event), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          <% end %>
        </div>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/_search_form.html.erb
<%= form_with(url: url_for, method: :get) do |f| %>
  <h5>Search</h5>
  <div class="row mb-2">
    <div class="col-2">
      <%= f.label :customer, 'Customer' %>
    </div>
    <div class="col">
      <%= f.select(:customer, Customer.order(:first_name).map { |c| [c.name, c.id] }, { selected: filter_params[:customer], include_blank: 'Any' }, { class: 'form-select form-select-sm', multiple: true }) %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-2">
      <%= f.label :event_type, 'Event Theme' %>
    </div>
    <div class="col">
      <%= f.select(:event_type, EventType.order(:name).pluck(:name, :id), { selected: filter_params[:event_type], include_blank: 'Any' }, { class: 'form-select form-select-sm', multiple: true }) %>
    </div>
  </div>
  <div class="row mb-2">
    <%= f.label 'Start Date from', class: 'col-2' %>
    <%= f.datetime_select(:start_from, {selected: filter_params[:start_from], prompt: true}, { class: "form-select form-select-sm col mr-1 ml-1 w-auto" }) %>
  </div>
  <div class="row mb-2">
    <%= f.label 'Start Date to', class: 'col-2' %>
    <%= f.datetime_select(:start_to, {selected: filter_params[:start_to], prompt: true}, { class: "form-select form-select-sm col mr-1 ml-1 w-auto" }) %>
  </div>
  <div class="row mb-2">
    <%= f.label 'Finish Date from', class: 'col-2' %>
    <%= f.datetime_select(:finish_from, {selected: filter_params[:finish_from], prompt: true}, { class: "form-select form-select-sm col mr-1 ml-1 w-auto" }) %>
  </div>
  <div class="row mb-2">
    <%= f.label 'Finish Date to', class: 'col-2' %>
    <%= f.datetime_select(:finish_to, {selected: filter_params[:finish_to], prompt: true}, { class: "form-select form-select-sm col mr-1 ml-1 w-auto" }) %>
  </div>
  <div class="row">
    <div class="col flex justify-center mt-4">
      <%= f.submit "Search", { class: 'btn btn-primary' } %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= render "form" %>

app/views/events/index.html.erb
<div class="px-8 py-6 rounded shadow bg-white">
  <%= render "search_form" %>
  <% if @events.empty? %>
    Your search did not find any results
  <% else %>
    <table class="w-full leading-10 table table-hover">
      <thead class="text-left border-b">
        <tr class="pb-1">
          <th scope="col">Customer</th>
          <th scope="col">Event Theme</th>
          <th scope="col">Event Time</th>
          <th scope="col" colspan="3">&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.customer.name %></td>
            <td><%= event.event_type.name %></td>
            <td><%= event.start.strftime("%b %e, %l:%M %p") %> - <%= event.finish.strftime("%b %e, %l:%M %p") %></td>
            <td><%= link_to "Edit", edit_event_path(event), class: "btn btn-primary" %></td>
            <td><%= link_to "View", event_path(event), class: "btn btn-success" %></td>
            <td><%= link_to 'Delete', event_path(event), data: {confirm: 'Are you sure?'}, method: :delete, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class="flex justify-center mt-4">
    <%= link_to "Create Event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<%= render "form" %>

app/views/events/show.html.erb
<div class="mx-auto px-8 py-6 rounded shadow bg-white">
  <div class="flex flex-col space-y-4">
    <div class="flex items-center justify-between bg-gray-100 py-3 px-6 rounded">
      <span class="font-bold">
        Event Theme
      </span>
      <span>
        <%= @event.event_type.name %>
      </span>
    </div>

    <div class="flex items-center justify-between bg-gray-100 py-3 px-6 rounded">
      <span class="font-bold">
        Customer
      </span>
      <span>
        <%= @event.customer.name %>
      </span>
    </div>

    <div class="flex items-center justify-between bg-gray-100 py-3 px-6 rounded">
      <span class="font-bold">
        Start
      </span>
      <span>
        <%= @event.start.strftime("%b %e, %l:%M %p") %>
      </span>
    </div>

    <div class="flex items-center justify-between bg-gray-100 py-3 px-6 rounded">
      <span class="font-bold">
        Finish
      </span>
      <span>
        <%= @event.finish.strftime("%b %e, %l:%M %p") %>
      </span>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ugly Duckling Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-100 text-gray-900 tracking-wider leading-normal">
    <div class="container mx-auto max-w-screen-lg px-4">
      <!-- nav -->
      <div class="flex justify-between my-8 font-sans font-bold break-normal text-2xl">
        <h1 class="text-green-600"><%= link_to "Ugly Duckling Events", root_path %></h1>
        <%= link_to "Events", events_path, class: "underline hover:no-underline" %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>